// ✅ OPTIMIZED: LessonAIQuestionsPage.tsx with Pagination & Lazy Loading

import React, { useState, useMemo, useEffect } from "react";
import LessonAIQuestions from "../components/LessonAIQuestions";
import { useGetEnrolledSubjects } from "../../subjects/api/subjectsApi";
import { useAuth } from "../../auth/useAuth";
import { Filter, X, ChevronLeft, ChevronRight } from "lucide-react";

const LessonAIQuestionsPage: React.FC = () => {
  const { user } = useAuth();
  const { data: enrolledSubjects, isLoading } = useGetEnrolledSubjects();

  // ✅ Filter states
  const [selectedSubjectId, setSelectedSubjectId] = useState<number | null>(null);
  const [selectedWeek, setSelectedWeek] = useState<string | null>(null);
  const [showFilters, setShowFilters] = useState(true);

  // ✅ Pagination states
  const [currentPage, setCurrentPage] = useState(1);
  const [questionsPerPage, setQuestionsPerPage] = useState(10);

  // Extract allowed subject IDs from backend
  const subjectIds = useMemo(() => {
    if (!enrolledSubjects) return [];
    return enrolledSubjects.map((s) => s.id);
  }, [enrolledSubjects]);

  // ✅ Reset to page 1 when filters change
  useEffect(() => {
    setCurrentPage(1);
  }, [selectedSubjectId, selectedWeek]);

  // ✅ Filter: Only selected subject (or all if none selected)
  const filteredSubjectIds = useMemo(() => {
    if (selectedSubjectId) {
      return [selectedSubjectId];
    }
    return subjectIds;
  }, [selectedSubjectId, subjectIds]);

  // ✅ Available weeks (1-10 for now, can be dynamic)
  const availableWeeks = useMemo(() => {
    return Array.from({ length: 10 }, (_, i) => ({
      value: `Week${i + 1}`,
      label: `Week ${i + 1}`,
    }));
  }, []);

  // ✅ Reset filters and pagination
  const handleResetFilters = () => {
    setSelectedSubjectId(null);
    setSelectedWeek(null);
    setCurrentPage(1);
  };

  // ✅ Handle filter change - reset to page 1
  const handleSubjectChange = (subjectId: number | null) => {
    setSelectedSubjectId(subjectId);
    setCurrentPage(1);
  };

  const handleWeekChange = (week: string | null) => {
    setSelectedWeek(week);
    setCurrentPage(1);
  };

  // ✅ Check if filters are active
  const hasActiveFilters = selectedSubjectId !== null || selectedWeek !== null;

  // If not logged in
  if (!user) {
    return (
      <div className="p-6">
        <div className="bg-red-50 border border-red-200 rounded-lg p-4">
          <p className="text-red-600 font-medium">You are not logged in.</p>
        </div>
      </div>
    );
  }

  // Loading subjects enrollment
  if (isLoading) {
    return (
      <div className="p-6 flex items-center justify-center min-h-[300px]">
        <div className="text-center">
          <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-purple-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading subject access...</p>
        </div>
      </div>
    );
  }

  // No enrolled subjects
  if (subjectIds.length === 0) {
    return (
      <div className="p-6">
        <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
          <p className="text-amber-700 font-medium">
            You are not enrolled in any subjects.
          </p>
          <p className="text-amber-600 text-sm mt-1">
            Contact your school administrator if this seems incorrect.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-4 max-w-6xl mx-auto space-y-6">
      {/* Header */}
      <div className="bg-gradient-to-r from-indigo-50 to-purple-50 rounded-lg p-6 border border-purple-200">
        <h1 className="text-3xl font-bold text-gray-900 mb-1">
          🤖 AI Practice Questions
        </h1>
        <p className="text-gray-600">
          Practice questions generated by AI for your enrolled subjects.
        </p>
      </div>

      {/* Filter Section */}
      <div className="bg-white rounded-lg border border-gray-200 shadow-sm">
        {/* Filter Header */}
        <div className="px-4 py-3 border-b border-gray-200 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Filter className="w-5 h-5 text-indigo-600" />
            <h3 className="font-semibold text-gray-900">Filters</h3>
            {hasActiveFilters && (
              <span className="px-2 py-1 bg-indigo-100 text-indigo-700 text-xs rounded-full font-medium">
                {[selectedSubjectId ? 1 : 0, selectedWeek ? 1 : 0].reduce((a, b) => a + b, 0)} active
              </span>
            )}
          </div>

          <div className="flex items-center gap-2">
            {hasActiveFilters && (
              <button
                onClick={handleResetFilters}
                className="text-sm text-gray-600 hover:text-gray-900 flex items-center gap-1"
              >
                <X className="w-4 h-4" />
                Clear All
              </button>
            )}
            <button
              onClick={() => setShowFilters(!showFilters)}
              className="text-sm text-indigo-600 hover:text-indigo-700 font-medium"
            >
              {showFilters ? "Hide" : "Show"}
            </button>
          </div>
        </div>

        {/* Filter Controls */}
        {showFilters && (
          <div className="p-4 space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              {/* Subject Filter */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Subject
                </label>
                <select
                  value={selectedSubjectId || ""}
                  onChange={(e) => handleSubjectChange(e.target.value ? Number(e.target.value) : null)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                >
                  <option value="">All Subjects ({enrolledSubjects?.length || 0})</option>
                  {enrolledSubjects?.map((subject) => (
                    <option key={subject.id} value={subject.id}>
                      {subject.name}
                    </option>
                  ))}
                </select>
              </div>

              {/* Week Filter */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Lesson Week
                </label>
                <select
                  value={selectedWeek || ""}
                  onChange={(e) => handleWeekChange(e.target.value || null)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                >
                  <option value="">All Weeks</option>
                  {availableWeeks.map((week) => (
                    <option key={week.value} value={week.value}>
                      {week.label}
                    </option>
                  ))}
                </select>
              </div>

              {/* Questions Per Page */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Questions Per Page
                </label>
                <select
                  value={questionsPerPage}
                  onChange={(e) => {
                    setQuestionsPerPage(Number(e.target.value));
                    setCurrentPage(1);
                  }}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
                >
                  <option value={5}>5 questions</option>
                  <option value={10}>10 questions</option>
                  <option value={20}>20 questions</option>
                  <option value={50}>50 questions</option>
                  <option value={100}>100 questions</option>
                </select>
              </div>
            </div>

            {/* Active Filters Display */}
            {hasActiveFilters && (
              <div className="flex flex-wrap gap-2 pt-2 border-t border-gray-200">
                <span className="text-sm text-gray-600">Active filters:</span>
                {selectedSubjectId && (
                  <span className="inline-flex items-center gap-1 px-3 py-1 bg-indigo-100 text-indigo-700 rounded-full text-sm">
                    {enrolledSubjects?.find(s => s.id === selectedSubjectId)?.name || "Subject"}
                    <button
                      onClick={() => handleSubjectChange(null)}
                      className="hover:bg-indigo-200 rounded-full p-0.5"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </span>
                )}
                {selectedWeek && (
                  <span className="inline-flex items-center gap-1 px-3 py-1 bg-purple-100 text-purple-700 rounded-full text-sm">
                    {availableWeeks.find(w => w.value === selectedWeek)?.label || selectedWeek}
                    <button
                      onClick={() => handleWeekChange(null)}
                      className="hover:bg-purple-200 rounded-full p-0.5"
                    >
                      <X className="w-3 h-3" />
                    </button>
                  </span>
                )}
              </div>
            )}
          </div>
        )}
      </div>

      {/* Questions Display with Pagination */}
      <LessonAIQuestions 
        subjectIds={filteredSubjectIds} 
        selectedWeek={selectedWeek}
        currentPage={currentPage}
        questionsPerPage={questionsPerPage}
        onPageChange={setCurrentPage}
      />
    </div>
  );
};

export default LessonAIQuestionsPage;